name: Sign project with ansible-sign
on:
  #push:
  workflow_dispatch:
jobs:
  ansible-sign:
    name: Sign project repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ansible-sign
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Sign the project
        uses: relrod/ansible-sign-action@main
        with:
          commit-result: false
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
